name: Tag to Generate
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate datestamp
        id: timestamp
        run: |
          echo "timestamp=$(date '+%y-%m-%d-%H')" >> $GITHUB_OUTPUT

      - name: Bump version and push tag
        uses: laputansoft/github-tag-action@v4.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'generate/${{ steps.timestamp.outputs.timestamp }}'
