name: Tag to Generate
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ssh-key: "${{ secrets.SSH_KEY }}"

      - name: Generate datestamp
        id: timestamp
        run: |
          echo "timestamp=$(date '+%y-%m-%d-%H')" >> $GITHUB_OUTPUT

      - name: Push Git Tag
        run: |
          echo "${{ secrets.SSH_KEY }}" > ssh_key
          chmod 600 ssh_key

          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag -m "Automated Run" 'generate/${{ steps.timestamp.outputs.timestamp }}'
          GIT_SSH_COMMAND="ssh -i ssh_key" git push origin 'generate/${{ steps.timestamp.outputs.timestamp }}'
