name: Tag to Generate
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate datestamp
        id: timestamp
        run: |
          echo "timestamp=$(date '+%y-%m-%d-%H')" >> $GITHUB_OUTPUT

      - name: Push Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag 'generate/${{ steps.timestamp.outputs.timestamp }}'
          git push origin 'generate/${{ steps.timestamp.outputs.timestamp }}'
